import {
  AirConditionerIcon,
  ShowerWCIcon,
  TVIcon,
  KitchenIcon,
  BedsIcon,
  CDIcon,
  RadioIcon,
  ShowerIcon,
  ToiletIcon,
  FreezerIcon,
  HobIcon,
  MicrowaveIcon,
  GasIcon,
  WaterIcon,
} from 'components/Icons';

export const cardDetailsIcon = {
  airConditioner: <AirConditionerIcon />,
  bathroom: <ShowerWCIcon />,
  kitchen: <KitchenIcon />,
  beds: <BedsIcon />,
  TV: <TVIcon />,
  CD: <CDIcon />,
  radio: <RadioIcon />,
  shower: <ShowerIcon />,
  toilet: <ToiletIcon />,
  freezer: <FreezerIcon />,
  hob: <HobIcon />,
  microwave: <MicrowaveIcon />,
  gas: <GasIcon />,
  water: <WaterIcon />,
};
